<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NotaFiscal extends Model
{
    protected $connection = 'srv_prologos';
    protected $table  = '';
    public $timestamps = false;
    public $incrementing = false;
    protected $primaty = 'NUMDOC';

    protected $fillable = ['NUMDOC' ,'TIPDOC' ,'CODCAD' ,'CODUSU' ,'STATDOC' ,'DESTINO' ,'ATIVIDADE' ,'TIPOPER' ,'FLAGCR' ,'FLAGCP' ,'FLAGLF' ,'FLAGEN' ,'FLAGCT' ,'FLAGDT' ,'FLAGED' ,'FLAGEF' ,'FLAGEC' ,'FLAGES' ,'FLAGPM' ,'FLAGRT' ,'FLAGEV' ,'FLAGCV' ,'MODALIDADE' ,'PORC_PREPAGO' ,'DESC_PREPAGO' ,'ESPDOC' ,'MODDOC' ,'BALICM' ,'REDICM' ,'APLIC_ICM' ,'APLIC_IPI' ,'EVENTO_CTB' ,'DTEMIS' ,'DTMOV' ,'TOTDESCONTO' ,'TOTICMST' ,'TOTMERCADORIA' ,'TOTSERVICOS' ,'TOTFRETE' ,'TOTSEGURO' ,'TOTOUTRAS' ,'TOTIPI' ,'TOTIRRF' ,'VALTOTDOC' ,'TOTPREPAGO' ,'MA_DEMANDA' ,'LOCAL_ENTREGA' ,'DTORDEM_FATURAR' ,'DTSAIDA' ,'CODTRAN' ,'TIPOFRETE' ,'PLACA_VEICULO' ,'QTDVOL' ,'ESPVOL' ,'PESO_BRUTO' ,'PESO_LIQUIDO' ,'INDCOMIS' ,'CODVND' ,'ATENDENTE' ,'TIPCOMIS' ,'COMISSAO_VND' ,'TIPOPERDA_IND' ,'PORCPERDA_IND' ,'TIPOPERDA_DESC' ,'DESCONTO_APLICADO' ,'PORCPERDA_DESC' ,'COMISSAO_ATEND' ,'EMPENHO_OK' ,'SIT_CRED' ,'CODUSU_CRED' ,'SIT_COND' ,'CODUSU_COND' ,'SIT_PRECO' ,'CODUSU_PRECO' ,'TPEMISNF' ,'TPAGRUPA' ,'MLD_GUERRA' ,'ECF_NUMMAQ' ,'ECF_NUMCUPOM' ,'NF_NUMNF' ,'NF_SERIE' ,'UFFORCLI' ,'CONTRIBUINTE' ,'CGC_CPF' ,'IEST' ,'IMUN' ,'CFO_ICMT1' ,'ALIQ_ICMT1' ,'BASECALC_ICMT1' ,'VALOR_ICMT1' ,'CFO_ICMT2' ,'ALIQ_ICMT2' ,'BASECALC_ICMT2' ,'VALOR_ICMT2' ,'CFO_ICMT3' ,'ALIQ_ICMT3' ,'BASECALC_ICMT3' ,'VALOR_ICMT3' ,'CFO_ICMT4' ,'ALIQ_ICMT4' ,'BASECALC_ICMT4' ,'VALOR_ICMT4' ,'CFO_ICMT5' ,'ALIQ_ICMT5' ,'BASECALC_ICMT5' ,'VALOR_ICMT5' ,'CFO_ICMI1' ,'BASECALC_ICMI1' ,'CFO_ICMO1' ,'BASECALC_ICMO1' ,'CFO_ICMI2' ,'BASECALC_ICMI2' ,'CFO_ICMO2' ,'BASECALC_ICMO2' ,'CFO_ICMST' ,'BASECALC_ICMST' ,'VALOR_ICMST' ,'RAT_FRETEST' ,'RAT_SEGUROST' ,'RAT_OUTRASST' ,'CFO_IPIT1' ,'BASECALC_IPIT1' ,'VALOR_IPIT1' ,'BASECALC_IPII1' ,'BASECALC_IPIO1' ,'CFO_IPIT2' ,'BASECALC_IPIT2' ,'VALOR_IPIT2' ,'BASECALC_IPII2' ,'BASECALC_IPIO2' ,'OBS_LF1' ,'OBS_LF2' ,'DIRF_IRRF' ,'BASE_IRRF' ,'ALIQ_IRRF' ,'NUMFAT' ,'FORMA_PGTO' ,'SITUACAO_CR' ,'PORTADOR_CR' ,'CODVCT' ,'FATORPRAZO' ,'DTVCTO_1' ,'DTVCTO_2' ,'DTVCTO_3' ,'DTVCTO_4' ,'DTVCTO_5' ,'DTVCTO_6' ,'DTVCTO_7' ,'DTVCTO_8' ,'VALPARC_1' ,'VALPARC_2' ,'VALPARC_3' ,'VALPARC_4' ,'VALPARC_5' ,'VALPARC_6' ,'VALPARC_7' ,'VALPARC_8' ,'REFERENCIA_CP' ,'LOCALPGTO_CP' ,'FLAG_IAD' ,'REPASSE' ,'DTVCTO_9' ,'DTVCTO_10' ,'DTVCTO_11' ,'DTVCTO_12' ,'DTVCTO_13' ,'DTVCTO_14' ,'DTVCTO_15' ,'DTVCTO_16' ,'DTVCTO_17' ,'DTVCTO_18' ,'DTVCTO_19' ,'DTVCTO_20' ,'DTVCTO_21' ,'DTVCTO_22' ,'DTVCTO_23' ,'DTVCTO_24' ,'VALPARC_9' ,'VALPARC_10' ,'VALPARC_11' ,'VALPARC_12' ,'VALPARC_13' ,'VALPARC_14' ,'VALPARC_15' ,'VALPARC_16' ,'VALPARC_17' ,'VALPARC_18' ,'VALPARC_19' ,'VALPARC_20' ,'VALPARC_21' ,'VALPARC_22' ,'VALPARC_23' ,'VALPARC_24' ,'BASECALC_ICMGNRE' ,'VALOR_ICMGNRE' ,'CFO_ICMI3' ,'BASECALC_ICMI3' ,'CFO_ICMO3' ,'BASECALC_ICMO3' ,'CFO_ICMI4' ,'BASECALC_ICMI4' ,'CFO_ICMO4' ,'BASECALC_ICMO4' ,'CFO_ICMST2' ,'BASECALC_ICMST2' ,'VALOR_ICMST2' ,'RAT_FRETEST2' ,'RAT_SEGUROST2' ,'RAT_OUTRASST2' ,'CFO_IPIT3' ,'BASECALC_IPIT3' ,'VALOR_IPIT3' ,'BASECALC_IPII3' ,'BASECALC_IPIO3' ,'CFO_IPIT4' ,'BASECALC_IPIT4' ,'VALOR_IPIT4' ,'BASECALC_IPII4' ,'BASECALC_IPIO4' ,'APLIC_PIS' ,'TOTAGREGADO' ,'SEFAZ_OK' ,'CHAVE_NFE44' ,'FLAGDP' ,'UF_PLACA'];

    public function acessaNotas($estabelecimento, $data = null){

    	if (is_null($data)){
    		$timestamp = time();
    	}
    	else{
    		$timestamp = strtotime($data);
    	}

    	DB::connection('srv_prologos')->table('DUM' . $estabelecimento . "_" .  date("y", $timestamp) . date("m", $timestamp) . "2");
    }
}
